 # Commands resolve the action from TPM's installed plugin directory at run time.
run-shell 'plugin_dir="${TMUX_PLUGIN_MANAGER_PATH%/}/tmux-awesome-sidebar"; [ -x "$plugin_dir/scripts/action" ] || plugin_dir="${TMUX_PLUGIN_MANAGER_PATH%/}"; key=$(tmux show-option -gqv @awesome_sidebar_key); [ -n "$key" ] || key=S; tmux bind-key -T prefix "$key" run-shell "\"$plugin_dir/scripts/action\" enter '\''#{session_id}'\'' '\''#{window_id}'\'' '\''#{pane_id}'\'' '\''#{client_name}'\''"'
run-shell -b 'plugin_dir="${TMUX_PLUGIN_MANAGER_PATH%/}/tmux-awesome-sidebar"; [ -x "$plugin_dir/scripts/action" ] || plugin_dir="${TMUX_PLUGIN_MANAGER_PATH%/}"; "$plugin_dir/scripts/action" auto-enable'
bind-key -T awesome-sidebar j run-shell 'plugin_dir="${TMUX_PLUGIN_MANAGER_PATH%/}/tmux-awesome-sidebar"; [ -x "$plugin_dir/scripts/action" ] || plugin_dir="${TMUX_PLUGIN_MANAGER_PATH%/}"; "$plugin_dir/scripts/action" navigate "#{pane_id}" down' \; switch-client -T awesome-sidebar
bind-key -T awesome-sidebar k run-shell 'plugin_dir="${TMUX_PLUGIN_MANAGER_PATH%/}/tmux-awesome-sidebar"; [ -x "$plugin_dir/scripts/action" ] || plugin_dir="${TMUX_PLUGIN_MANAGER_PATH%/}"; "$plugin_dir/scripts/action" navigate "#{pane_id}" up' \; switch-client -T awesome-sidebar
bind-key -T awesome-sidebar Up run-shell 'plugin_dir="${TMUX_PLUGIN_MANAGER_PATH%/}/tmux-awesome-sidebar"; [ -x "$plugin_dir/scripts/action" ] || plugin_dir="${TMUX_PLUGIN_MANAGER_PATH%/}"; "$plugin_dir/scripts/action" navigate "#{pane_id}" up' \; switch-client -T awesome-sidebar
bind-key -T awesome-sidebar Down run-shell 'plugin_dir="${TMUX_PLUGIN_MANAGER_PATH%/}/tmux-awesome-sidebar"; [ -x "$plugin_dir/scripts/action" ] || plugin_dir="${TMUX_PLUGIN_MANAGER_PATH%/}"; "$plugin_dir/scripts/action" navigate "#{pane_id}" down' \; switch-client -T awesome-sidebar
bind-key -T awesome-sidebar h run-shell 'plugin_dir="${TMUX_PLUGIN_MANAGER_PATH%/}/tmux-awesome-sidebar"; [ -x "$plugin_dir/scripts/action" ] || plugin_dir="${TMUX_PLUGIN_MANAGER_PATH%/}"; "$plugin_dir/scripts/action" navigate "#{pane_id}" collapse' \; switch-client -T awesome-sidebar
bind-key -T awesome-sidebar l run-shell 'plugin_dir="${TMUX_PLUGIN_MANAGER_PATH%/}/tmux-awesome-sidebar"; [ -x "$plugin_dir/scripts/action" ] || plugin_dir="${TMUX_PLUGIN_MANAGER_PATH%/}"; "$plugin_dir/scripts/action" navigate "#{pane_id}" expand' \; switch-client -T awesome-sidebar
bind-key -T awesome-sidebar g run-shell 'plugin_dir="${TMUX_PLUGIN_MANAGER_PATH%/}/tmux-awesome-sidebar"; [ -x "$plugin_dir/scripts/action" ] || plugin_dir="${TMUX_PLUGIN_MANAGER_PATH%/}"; "$plugin_dir/scripts/action" navigate "#{pane_id}" gg' \; switch-client -T awesome-sidebar
bind-key -T awesome-sidebar G run-shell 'plugin_dir="${TMUX_PLUGIN_MANAGER_PATH%/}/tmux-awesome-sidebar"; [ -x "$plugin_dir/scripts/action" ] || plugin_dir="${TMUX_PLUGIN_MANAGER_PATH%/}"; "$plugin_dir/scripts/action" navigate "#{pane_id}" G' \; switch-client -T awesome-sidebar
bind-key -T awesome-sidebar Enter run-shell 'plugin_dir="${TMUX_PLUGIN_MANAGER_PATH%/}/tmux-awesome-sidebar"; [ -x "$plugin_dir/scripts/action" ] || plugin_dir="${TMUX_PLUGIN_MANAGER_PATH%/}"; "$plugin_dir/scripts/action" navigate "#{pane_id}" enter' \; switch-client -T awesome-sidebar
bind-key -T awesome-sidebar r run-shell 'plugin_dir="${TMUX_PLUGIN_MANAGER_PATH%/}/tmux-awesome-sidebar"; [ -x "$plugin_dir/scripts/action" ] || plugin_dir="${TMUX_PLUGIN_MANAGER_PATH%/}"; "$plugin_dir/scripts/action" refresh "#{session_id}" "#{window_id}" "#{pane_id}"' \; switch-client -T awesome-sidebar
bind-key -T awesome-sidebar a run-shell 'plugin_dir="${TMUX_PLUGIN_MANAGER_PATH%/}/tmux-awesome-sidebar"; [ -x "$plugin_dir/scripts/action" ] || plugin_dir="${TMUX_PLUGIN_MANAGER_PATH%/}"; "$plugin_dir/scripts/action" session-new "#{@awesome_sidebar_group}" "#{pane_current_path}" "New session" "#{pane_id}"' \; switch-client -T awesome-sidebar
bind-key -T awesome-sidebar s run-shell 'plugin_dir="${TMUX_PLUGIN_MANAGER_PATH%/}/tmux-awesome-sidebar"; [ -x "$plugin_dir/scripts/action" ] || plugin_dir="${TMUX_PLUGIN_MANAGER_PATH%/}"; "$plugin_dir/scripts/action" session-select "#{@awesome_sidebar_group}" "#{window_id}" "#{pane_id}"' \; switch-client -T awesome-sidebar
bind-key -T awesome-sidebar J run-shell 'plugin_dir="${TMUX_PLUGIN_MANAGER_PATH%/}/tmux-awesome-sidebar"; [ -x "$plugin_dir/scripts/action" ] || plugin_dir="${TMUX_PLUGIN_MANAGER_PATH%/}"; "$plugin_dir/scripts/action" navigate "#{pane_id}" down' \; switch-client -T awesome-sidebar
bind-key -T awesome-sidebar K run-shell 'plugin_dir="${TMUX_PLUGIN_MANAGER_PATH%/}/tmux-awesome-sidebar"; [ -x "$plugin_dir/scripts/action" ] || plugin_dir="${TMUX_PLUGIN_MANAGER_PATH%/}"; "$plugin_dir/scripts/action" navigate "#{pane_id}" up' \; switch-client -T awesome-sidebar
bind-key -T awesome-sidebar / command-prompt -i -p 'Search' -T search 'set-option -p @awesome_sidebar_pending_query "%%%" \; run-shell "plugin_dir=\"${TMUX_PLUGIN_MANAGER_PATH%/}/tmux-awesome-sidebar\"; [ -x \"$plugin_dir/scripts/action\" ] || plugin_dir=\"${TMUX_PLUGIN_MANAGER_PATH%/}\"; \"$plugin_dir/scripts/action\" search-update \"#{@awesome_sidebar_group}\" \"#{pane_id}\""'
bind-key -T awesome-sidebar q run-shell 'plugin_dir="${TMUX_PLUGIN_MANAGER_PATH%/}/tmux-awesome-sidebar"; [ -x "$plugin_dir/scripts/action" ] || plugin_dir="${TMUX_PLUGIN_MANAGER_PATH%/}"; "$plugin_dir/scripts/action" disable "#{session_id}" "#{window_id}" "#{pane_id}"'
bind-key -T awesome-sidebar Escape run-shell 'plugin_dir="${TMUX_PLUGIN_MANAGER_PATH%/}/tmux-awesome-sidebar"; [ -x "$plugin_dir/scripts/action" ] || plugin_dir="${TMUX_PLUGIN_MANAGER_PATH%/}"; "$plugin_dir/scripts/action" search-clear "#{@awesome_sidebar_group}" "#{pane_id}"' \; switch-client -T prefix
# shellcheck disable=SC2035
bind-key -T awesome-sidebar ? display-message 'j/k or arrows move, h/l collapse, Enter select, / search, q close'
set-hook -g 'after-split-window[99]' 'run-shell -b "plugin_dir=\"\${TMUX_PLUGIN_MANAGER_PATH%/}/tmux-awesome-sidebar\"; [ -x \"\$plugin_dir/scripts/action\" ] || plugin_dir=\"\${TMUX_PLUGIN_MANAGER_PATH%/}\"; \"\$plugin_dir/scripts/action\" refresh-from-hook"'
set-hook -g 'after-new-window[99]' 'run-shell -b "plugin_dir=\"\${TMUX_PLUGIN_MANAGER_PATH%/}/tmux-awesome-sidebar\"; [ -x \"\$plugin_dir/scripts/action\" ] || plugin_dir=\"\${TMUX_PLUGIN_MANAGER_PATH%/}\"; \"\$plugin_dir/scripts/action\" auto-enable"'
set-hook -g 'after-kill-pane[99]' 'run-shell -b "plugin_dir=\"\${TMUX_PLUGIN_MANAGER_PATH%/}/tmux-awesome-sidebar\"; [ -x \"\$plugin_dir/scripts/action\" ] || plugin_dir=\"\${TMUX_PLUGIN_MANAGER_PATH%/}\"; \"\$plugin_dir/scripts/action\" refresh-from-hook"'
set-hook -g 'pane-exited[99]' 'run-shell -b "plugin_dir=\"\${TMUX_PLUGIN_MANAGER_PATH%/}/tmux-awesome-sidebar\"; [ -x \"\$plugin_dir/scripts/action\" ] || plugin_dir=\"\${TMUX_PLUGIN_MANAGER_PATH%/}\"; \"\$plugin_dir/scripts/action\" refresh-from-hook"'
set-hook -g 'window-linked[99]' 'run-shell -b "plugin_dir=\"\${TMUX_PLUGIN_MANAGER_PATH%/}/tmux-awesome-sidebar\"; [ -x \"\$plugin_dir/scripts/action\" ] || plugin_dir=\"\${TMUX_PLUGIN_MANAGER_PATH%/}\"; \"\$plugin_dir/scripts/action\" refresh-from-hook"'
set-hook -g 'window-renamed[99]' 'run-shell -b "plugin_dir=\"\${TMUX_PLUGIN_MANAGER_PATH%/}/tmux-awesome-sidebar\"; [ -x \"\$plugin_dir/scripts/action\" ] || plugin_dir=\"\${TMUX_PLUGIN_MANAGER_PATH%/}\"; \"\$plugin_dir/scripts/action\" refresh-from-hook"'
set-hook -g 'session-closed[99]' 'run-shell -b "plugin_dir=\"\${TMUX_PLUGIN_MANAGER_PATH%/}/tmux-awesome-sidebar\"; [ -x \"\$plugin_dir/scripts/action\" ] || plugin_dir=\"\${TMUX_PLUGIN_MANAGER_PATH%/}\"; \"\$plugin_dir/scripts/action\" refresh-from-hook"'
